user:
  VALID_EMAIL_REGEX: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  NAME_MAX_LENGTH: 50
  EMAIL_MIN_LENGTH: 10
  EMAIL_MAX_LENGTH: 255
  PASSWORD_MIN_LENGTH: 8
book:
  MIN_RATING: 1
  MAX_RATING: 5
  MIN_TOTAL_PAGES: 0
  BOOK_PER_PAGE: 24
review:
  REVIEW_PER_PAGE: 5
follow:
  USER_PER_PAGE: 24
time_zone: "Asia/Ho_Chi_Minh"
image:
  ACCEPT_IMG_TYPE: "image/jpg,image/jpeg,image/gif,image/png"
  IMG_EXTENSION_ALLOW: <%= %w(jpg jpeg gif png) %>
  PICTURE_MAX_SIZE: 5
